
import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "ru" | "uk";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    applicationTitle: "Video Tool",
    applicationDescription: "High-quality video conversion tools. No upload required - everything happens in your browser.",
    batchProcessingTip: "If you need to convert more than 7 videos at once, open several tabs of the site in parallel.",
    uploadVideo: "Upload Video",
    uploadYourVideos: "Upload your videos",
    dropIt: "Drop it!",
    dragDropMultiple: "Drag and drop multiple video files or click here",
    dragDropSingle: "Drag and drop your video file or click here",
    browseFiles: "Browse files",
    dragAndDrop: "Drag and drop your video here",
    orBrowse: "or browse your files",
    fileType: "MP4, WebM, MOV up to 50MB",
    removeVideo: "Remove",
    convertToGif: "Convert to GIF",
    downloadGif: "Download GIF",
    processing: "Processing...",
    selectQuality: "Quality:",
    selectSize: "Size:",
    selectFps: "FPS:",
    low: "Low",
    medium: "Medium",
    high: "High",
    small: "Small",
    original: "Original",
    large: "Large",
    downloadAs: "Download as:",
    createNew: "Create New",
    gifCreated: "GIF Created!",
    changeSettings: "Change Settings",
    ffmpegError: "Failed to load video processing tools.",
    retryLoading: "Try Again",
    browserSecurityError: "Browser security is blocking required functionality.",
    crossOriginIsolation: "This site requires cross-origin isolation to be enabled for optimal performance.",
    loadingFFmpeg: "Loading video processing tools...",
    seconds: "Seconds",
    toggleTheme: "Toggle theme",
    darkMode: "Switch to dark mode",
    lightMode: "Switch to light mode",
    privacyNotice: "Your privacy is important to us",
    fileNotStored: "We do not store your files",
    
    quality: "Quality",
    frameRate: "Frame Rate",
    fps: "fps",
    smooth: "Smooth",
    detailed: "Detailed",
    highDetail: "High Detail",
    speed: "Speed",
    slowMotion: "Slow Motion",
    normal: "Normal",
    fast: "Fast",
    videoSegments: "Video Segments",
    standardMode: "Standard Mode",
    advancedMode: "Advanced Mode",
    noSplitting: "No Splitting",
    segments: "Segments",
    advancedUpTo: "Up to 60 segments",
    standardUpTo: "Up to 20 segments",
    dividesVideo: "Divides video into equal segments",
    parts: "Parts",
    noParts: "No Parts",
    warning: "Warning: High segment count may impact performance",
    dimensions: "Dimensions",
    maintainAspectRatio: "Maintain Aspect Ratio",
    width: "Width",
    height: "Height",
    auto: "Auto",
    heightWillBeCalculated: "Height will be calculated automatically to maintain the aspect ratio",
    settings: "Settings",
    preview: "Preview",
    videoToGif: "Video to GIF",
    videoToPieces: "Video to Pieces",
    largeGifWarning: "Large GIF Warning",
    gifsTooLarge: "GIFs are too large",
    sizeWarningDescription: "GIFs may cause performance issues and take longer to download",
    
    convertAgain: "Convert Again",
    gifPreview: "GIF Preview",
    downloadSegment: "Download Segment",
    downloadAll: "Download All",
    downloadAsZIP: "Download as ZIP",
    creatingZip: "Creating ZIP...",
    preparing: "Preparing...",
    converting: "Converting...",
    convertedGif: "Converted GIF",
    convertedGifs: "Converted GIFs",
    
    pleaseUploadVideo: "Please upload a video first",
    uploadVideoFirst: "Upload video first",
    noSegmentsYet: "No segments yet. Click 'Add Segment' to start",
    addSegment: "Add Segment",
    segment: "Segment",
    remove: "Remove",
    startTime: "Start Time",
    endTime: "End Time",
    cannotCutVideo: "Cannot cut video. Please check your settings.",
    cutVideo: "Cut Video",
    
    sequentialConversion: "Sequential Conversion",
    sequentialDescription: "Convert videos into equal segments of fixed duration",
    segmentLength: "Segment Length",
    conversionStatus: "Conversion Status",
    filesToProcess: "Files to Process",
    filesSelected: "files selected",
    currentlyProcessing: "Currently Processing",
    segmentsCreated: "Segments Created",
    startSequentialConversion: "Start Conversion",
    downloadAllAsZip: "Download All as ZIP",
    "5seconds": "5 Seconds",
    "10seconds": "10 Seconds",
    customSeconds: "Custom Seconds",
    allVideosProcessed: "All videos processed",
    uploadFilesFirst: "Upload files first",
    noFilesSelected: "No files selected",
    error: "Error",
    failedToConvert: "Failed to convert",
    ffmpegNotLoaded: "Video processing tools not loaded",
    noGifsToDownload: "No GIFs to download",
    downloadError: "Download error",
    tabSwitchWarning: "⚠️ IMPORTANT: Do not switch to other tabs during video processing! This may stop the conversion process."
  },
  ru: {
    applicationTitle: "Video Tool",
    applicationDescription: "Инструменты для конвертации видео высокого качества. Без загрузки на сервер - все происходит в вашем браузере.",
    batchProcessingTip: "Если вам нужно конвертировать больше чем 7 видео за 1 раз, откройте несколько вкладок сайта параллельно.",
    uploadVideo: "Загрузить видео",
    uploadYourVideos: "Загрузите ваши видео",
    dropIt: "Отпускайте!",
    dragDropMultiple: "Перетащите видеофайлы сюда или нажмите",
    dragDropSingle: "Перетащите видеофайл сюда или нажмите",
    browseFiles: "Выбрать файлы",
    dragAndDrop: "Перетащите видео сюда",
    orBrowse: "или выберите файл",
    fileType: "MP4, WebM, MOV до 50МБ",
    removeVideo: "Удалить",
    convertToGif: "Конвертировать в GIF",
    downloadGif: "Скачать GIF",
    processing: "Обработка...",
    selectQuality: "Качество:",
    selectSize: "Размер:",
    selectFps: "Кадр/сек:",
    low: "Низкое",
    medium: "Среднее",
    high: "Высокое",
    small: "Маленький",
    original: "Оригинал",
    large: "Большой",
    downloadAs: "Скачать как:",
    createNew: "Создать новый",
    gifCreated: "GIF создан!",
    changeSettings: "Изменить настройки",
    ffmpegError: "Не удалось загрузить инструменты обработки видео.",
    retryLoading: "Попробовать снова",
    browserSecurityError: "Безопасность браузера блокирует необходимую функциональность.",
    crossOriginIsolation: "Этот сайт требует включения изоляции перекрестного происхождения для оптимальной производительности.",
    loadingFFmpeg: "Загрузка инструментов обработки видео...",
    seconds: "Секунд",
    toggleTheme: "Переключить тему",
    darkMode: "Переключить на темную тему",
    lightMode: "Переключить на светлую тему",
    privacyNotice: "Ваша конфиденциальность важна для нас",
    fileNotStored: "Мы не храним ваши файлы",
    
    quality: "Качество",
    frameRate: "Частота кадров",
    fps: "кадр/сек",
    smooth: "Плавно",
    detailed: "Детально",
    highDetail: "Высокая детализация",
    speed: "Скорость",
    slowMotion: "Замедленно",
    normal: "Нормально",
    fast: "Быстро",
    videoSegments: "Сегменты видео",
    standardMode: "Стандартный режим",
    advancedMode: "Расширенный режим",
    noSplitting: "Без разделения",
    segments: "Сегменты",
    advancedUpTo: "До 60 сегментов",
    standardUpTo: "До 20 сегментов",
    dividesVideo: "Разделяет видео на равные сегменты",
    parts: "Частей",
    noParts: "Без разделения",
    warning: "Внимание: Большое количество сегментов может повлиять на производительность",
    dimensions: "Размеры",
    maintainAspectRatio: "Сохранять пропорции",
    width: "Ширина",
    height: "Высота",
    auto: "Авто",
    heightWillBeCalculated: "Высота будет рассчитана автоматически для сохранения пропорций",
    settings: "Настройки",
    preview: "Предпросмотр",
    videoToGif: "Видео в GIF",
    videoToPieces: "Видео на части",
    largeGifWarning: "Предупреждение о большом размере GIF",
    gifsTooLarge: "GIFs слишком большие",
    sizeWarningDescription: "Большие GIF могут вызвать проблемы с производительностью и дольше загружаться",
    
    convertAgain: "Конвертировать снова",
    gifPreview: "Предпросмотр GIF",
    downloadSegment: "Скачать сегмент",
    downloadAll: "Скачать все",
    downloadAsZIP: "Скачать как ZIP",
    creatingZip: "Создание ZIP...",
    preparing: "Подготовка...",
    converting: "Конвертация...",
    convertedGif: "Конвертированный GIF",
    convertedGifs: "Конвертированные GIF",
    
    pleaseUploadVideo: "Пожалуйста, сначала загрузите видео",
    uploadVideoFirst: "Сначала загрузите видео",
    noSegmentsYet: "Сегментов пока нет. Нажмите 'Добавить сегмент', чтобы начать",
    addSegment: "Добавить сегмент",
    segment: "Сегмент",
    remove: "Удалить",
    startTime: "Начальное время",
    endTime: "Конечное время",
    cannotCutVideo: "Невозможно разрезать видео. Пожалуйста, проверьте настройки.",
    cutVideo: "Разрезать видео",
    
    sequentialConversion: "Последовательная конвертация",
    sequentialDescription: "Конвертация видео в равные сегменты фиксированной длительности",
    segmentLength: "Длина сегмента",
    conversionStatus: "Статус конвертации",
    filesToProcess: "Файлы для обработки",
    filesSelected: "файлов выбрано",
    currentlyProcessing: "Обрабатывается",
    segmentsCreated: "Создано сегментов",
    startSequentialConversion: "Начать конвертацию",
    downloadAllAsZip: "Скачать всё как ZIP",
    "5seconds": "5 Секунд",
    "10seconds": "10 Секунд",
    customSeconds: "Произвольное количество секунд",
    allVideosProcessed: "Все видео обработаны",
    uploadFilesFirst: "Сначала загрузите файлы",
    noFilesSelected: "Файлы не выбраны",
    error: "Ошибка",
    failedToConvert: "Не удалось конвертировать",
    ffmpegNotLoaded: "Инструменты обработки видео не загружены",
    noGifsToDownload: "Нет GIF для скачивания",
    downloadError: "Ошибка скачивания",
    tabSwitchWarning: "⚠️ ВАЖНО: Не переключайтесь на другие вкладки во время обработки видео! Это может остановить процесс конвертации."
  },
  uk: {
    applicationTitle: "Video Tool",
    applicationDescription: "Інструменти для конвертації відео високої якості. Без завантаження на сервер - все відбувається у вашому браузері.",
    batchProcessingTip: "Якщо вам потрібно конвертувати більше 7 відео за раз, відкрийте кілька вкладок сайту паралельно.",
    uploadVideo: "Завантажити відео",
    uploadYourVideos: "Завантажте ваші відео",
    dropIt: "Відпускайте!",
    dragDropMultiple: "Перетягніть відеофайли сюди або натисніть",
    dragDropSingle: "Перетягніть відеофайл сюди або натисніть",
    browseFiles: "Вибрати файли",
    dragAndDrop: "Перетягніть відео сюди",
    orBrowse: "або виберіть файл",
    fileType: "MP4, WebM, MOV до 50МБ",
    removeVideo: "Видалити",
    convertToGif: "Конвертувати в GIF",
    downloadGif: "Завантажити GIF",
    processing: "Обробка...",
    selectQuality: "Якість:",
    selectSize: "Розмір:",
    selectFps: "Кадрів/сек:",
    low: "Низька",
    medium: "Середня",
    high: "Висока",
    small: "Малий",
    original: "Оригінал",
    large: "Великий",
    downloadAs: "Завантажити як:",
    createNew: "Створити новий",
    gifCreated: "GIF створено!",
    changeSettings: "Змінити налаштування",
    ffmpegError: "Не вдалося завантажити інструменти обробки відео.",
    retryLoading: "Спробувати знову",
    browserSecurityError: "Безпека браузера блокує необхідну функціональність.",
    crossOriginIsolation: "Цей сайт вимагає увімкнення ізоляції перехресного походження для оптимальної продуктивності.",
    loadingFFmpeg: "Завантаження інструментів обробки відео...",
    seconds: "Секунд",
    toggleTheme: "Перемкнути тему",
    darkMode: "Перемкнути на темну тему",
    lightMode: "Перемкнути на світлу тему",
    privacyNotice: "Ваша конфіденційність важлива для нас",
    fileNotStored: "Ми не зберігаємо ваші файли",
    
    quality: "Якість",
    frameRate: "Частота кадрів",
    fps: "кадрів/сек",
    smooth: "Плавно",
    detailed: "Детально",
    highDetail: "Висока деталізація",
    speed: "Швидкість",
    slowMotion: "Уповільнено",
    normal: "Звичайно",
    fast: "Швидко",
    videoSegments: "Сегменти відео",
    standardMode: "Стандартний режим",
    advancedMode: "Розширений режим",
    noSplitting: "Без поділу",
    segments: "Сегменти",
    advancedUpTo: "До 60 сегментів",
    standardUpTo: "До 20 сегментів",
    dividesVideo: "Розділяє відео на рівні сегменти",
    parts: "Частин",
    noParts: "Без поділу",
    warning: "Увага: Велика кількість сегментів може вплинути на продуктивність",
    dimensions: "Розміри",
    maintainAspectRatio: "Зберігати пропорції",
    width: "Ширина",
    height: "Висота",
    auto: "Авто",
    heightWillBeCalculated: "Висота буде розрахована автоматично для збереження пропорцій",
    settings: "Налаштування",
    preview: "Попередній перегляд",
    videoToGif: "Відео у GIF",
    videoToPieces: "Відео на частини",
    largeGifWarning: "Попередження про великий розмір GIF",
    gifsTooLarge: "GIF занадто великі",
    sizeWarningDescription: "Великі GIF можуть викликати проблеми з продуктивністю і довше завантажуватися",
    
    convertAgain: "Конвертувати знову",
    gifPreview: "Попередній перегляд GIF",
    downloadSegment: "Завантажити сегмент",
    downloadAll: "Завантажити все",
    downloadAsZIP: "Завантажити як ZIP",
    creatingZip: "Створення ZIP...",
    preparing: "Підготовка...",
    converting: "Конвертація...",
    convertedGif: "Конвертований GIF",
    convertedGifs: "Конвертовані GIF",
    
    pleaseUploadVideo: "Будь ласка, спочатку завантажте відео",
    uploadVideoFirst: "Спочатку завантажте відео",
    noSegmentsYet: "Сегментів поки немає. Натисніть 'Додати сегмент', щоб почати",
    addSegment: "Додати сегмент",
    segment: "Сегмент",
    remove: "Видалити",
    startTime: "Початковий час",
    endTime: "Кінцевий час",
    cannotCutVideo: "Неможливо розрізати відео. Будь ласка, перевірте налаштування.",
    cutVideo: "Розрізати відео",
    
    sequentialConversion: "Послідовна конвертація",
    sequentialDescription: "Конвертація відео в рівні сегменти фіксованої тривалості",
    segmentLength: "Довжина сегмента",
    conversionStatus: "Статус конвертації",
    filesToProcess: "Файли для обробки",
    filesSelected: "файлів вибрано",
    currentlyProcessing: "Обробляється",
    segmentsCreated: "Створено сегментів",
    startSequentialConversion: "Почати конвертацію",
    downloadAllAsZip: "Завантажити все як ZIP",
    "5seconds": "5 Секунд",
    "10seconds": "10 Секунд",
    customSeconds: "Довільна кількість секунд",
    allVideosProcessed: "Всі відео оброблені",
    uploadFilesFirst: "Спочатку завантажте файли",
    noFilesSelected: "Файли не вибрані",
    error: "Помилка",
    failedToConvert: "Не вдалося конвертувати",
    ffmpegNotLoaded: "Інструменти обробки відео не завантажені",
    noGifsToDownload: "Немає GIF для завантаження",
    downloadError: "Помилка завантаження",
    tabSwitchWarning: "⚠️ ВАЖЛИВО: Не перемикайтесь на інші вкладки під час обробки відео! Це може зупинити процес конвертації."
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "ru",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    if (!translations[language] || !translations[language][key]) {
      console.warn(`Missing translation for key: ${key}`);
      return translations.en[key] || key;
    }
    return translations[language][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
