
import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ru" | "uk";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    applicationTitle: "Video Tool",
    applicationDescription: "High-quality video conversion tools. No upload required - everything happens in your browser.",
    batchProcessingTip: "If you need to convert more than 7 videos at once, open several tabs of the site in parallel.",
    uploadVideo: "Upload Video",
    uploadYourVideos: "Upload your videos",
    dropIt: "Drop it!",
    dragDropMultiple: "Drag and drop multiple video files or click here",
    dragDropSingle: "Drag and drop your video file or click here",
    browseFiles: "Browse files",
    dragAndDrop: "Drag and drop your video here",
    orBrowse: "or browse your files",
    fileType: "MP4, WebM, MOV up to 50MB",
    removeVideo: "Remove",
    convertToGif: "Convert to GIF",
    downloadGif: "Download GIF",
    processing: "Processing...",
    selectQuality: "Quality:",
    selectSize: "Size:",
    selectFps: "FPS:",
    low: "Low",
    medium: "Medium",
    high: "High",
    small: "Small",
    original: "Original",
    large: "Large",
    downloadAs: "Download as:",
    createNew: "Create New",
    gifCreated: "GIF Created!",
    changeSettings: "Change Settings",
    ffmpegError: "Failed to load video processing tools.",
    retryLoading: "Try Again",
    browserSecurityError: "Browser security is blocking required functionality.",
    crossOriginIsolation: "This site requires cross-origin isolation to be enabled for optimal performance.",
    loadingFFmpeg: "Loading video processing tools...",
    seconds: "Seconds",
    toggleTheme: "Toggle theme",
    darkMode: "Switch to dark mode",
    lightMode: "Switch to light mode",
    privacyNotice: "Your privacy is important to us",
    fileNotStored: "We do not store your files",
    
    quality: "Quality",
    frameRate: "Frame Rate",
    fps: "fps",
    smooth: "Smooth",
    detailed: "Detailed",
    highDetail: "High Detail",
    speed: "Speed",
    slowMotion: "Slow Motion",
    normal: "Normal",
    fast: "Fast",
    videoSegments: "Video Segments",
    standardMode: "Standard Mode",
    advancedMode: "Advanced Mode",
    noSplitting: "No Splitting",
    segments: "Segments",
    advancedUpTo: "Up to 60 segments",
    standardUpTo: "Up to 20 segments",
    dividesVideo: "Divides video into equal segments",
    parts: "Parts",
    noParts: "No Parts",
    warning: "Warning: High segment count may impact performance",
    dimensions: "Dimensions",
    maintainAspectRatio: "Maintain Aspect Ratio",
    width: "Width",
    height: "Height",
    auto: "Auto",
    heightWillBeCalculated: "Height will be calculated automatically to maintain the aspect ratio",
    settings: "Settings",
    preview: "Preview",
    videoToGif: "Video to GIF",
    videoToPieces: "Video to Pieces",
    largeGifWarning: "Large GIF Warning",
    gifsTooLarge: "GIFs are too large",
    sizeWarningDescription: "GIFs may cause performance issues and take longer to download",
    
    convertAgain: "Convert Again",
    gifPreview: "GIF Preview",
    downloadSegment: "Download Segment",
    downloadAll: "Download All",
    downloadAsZIP: "Download as ZIP",
    creatingZip: "Creating ZIP...",
    preparing: "Preparing...",
    converting: "Converting...",
    convertedGif: "Converted GIF",
    convertedGifs: "Converted GIFs",
    
    pleaseUploadVideo: "Please upload a video first",
    uploadVideoFirst: "Upload video first",
    noSegmentsYet: "No segments yet. Click 'Add Segment' to start",
    addSegment: "Add Segment",
    segment: "Segment",
    remove: "Remove",
    startTime: "Start Time",
    endTime: "End Time",
    cannotCutVideo: "Cannot cut video. Please check your settings.",
    cutVideo: "Cut Video",
    
    sequentialConversion: "Sequential Conversion",
    sequentialDescription: "Convert videos into equal segments of fixed duration",
    segmentLength: "Segment Length",
    conversionStatus: "Conversion Status",
    filesToProcess: "Files to Process",
    filesSelected: "files selected",
    currentlyProcessing: "Currently Processing",
    segmentsCreated: "Segments Created",
    startSequentialConversion: "Start Conversion",
    downloadAllAsZip: "Download All as ZIP",
    "5seconds": "5 Seconds",
    "10seconds": "10 Seconds",
    customSeconds: "Custom Seconds",
    allVideosProcessed: "All videos processed",
    uploadFilesFirst: "Upload files first",
    noFilesSelected: "No files selected",
    error: "Error",
    failedToConvert: "Failed to convert",
    ffmpegNotLoaded: "Video processing tools not loaded",
    noGifsToDownload: "No GIFs to download",
    downloadError: "Download error",
    tabSwitchWarning: "⚠️ IMPORTANT: Do not switch to other tabs during video processing! This may stop the conversion process.",
    videoCutter: "Video Cutter",
    processingComplete: "Processing complete",
    settingsHelpText: "Adjust quality, frame rate and dimensions before converting",
    qualityTooltip: "Higher quality means a larger file size and slower conversion",
    fpsTooltip: "Frames per second: higher values give smoother motion but a larger file",
    pageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",

    download: "Download",
    convertedImages: "Converted Images",

    movToMp4Title: "MOV/HEVC to MP4 Converter",
    movToMp4Description: "Convert MOV and HEVC (H.265) files to compatible MP4 (H.264)",
    movToMp4DropDefault: "Click to select or drag and drop MOV file",
    movToMp4DropActive: "Drop MOV file here",
    movToMp4StepInit: "Initializing FFmpeg...",
    movToMp4StepProcessingFile: "Processing file...",
    movToMp4StepConverting: "Converting video...",
    movToMp4StepPreparing: "Preparing download...",
    movToMp4StepComplete: "Complete!",
    movToMp4ErrorTimeout: "Conversion timeout - file may be too complex or corrupted",
    movToMp4ErrorInvalidDrop: "Please drop a MOV or MP4 file",
    movToMp4ErrorHevc: "HEVC/H.265 video conversion failed. This codec can be challenging to process.",
    movToMp4ErrorTimeoutRetry: "Conversion timed out. Please try with a smaller file or different format.",
    movToMp4ErrorPrefix: "Conversion failed:",

    imgToJpgTitle: "Image to JPG Converter",
    imgToJpgDescription: "Convert HEIC, PNG, JPG, and other image formats to optimized JPG with best quality",
    safariNoticeTitle: "Safari User Notice",
    safariNoticeText: "uses a special download method for ZIP files to ensure reliable downloads. Large files may take a moment to process before downloading.",
    imgSuccessfullyConverted: "Successfully converted",
    imgFallback: "fallback",
    imgViaBrowser: "via browser",
    imgHeicUnsupported: "cannot be converted: HEIC not supported. Please use Windows Photos to export as JPG.",
    imgConversionFailedFor: "Conversion failed for",

    vidToJpgTitle: "VIDEO TO JPG",
    vidToJpgLoadingProcessor: "Loading video processor...",
    vidToJpgLoadingHint: "This may take a few seconds on first load.",
    vidToJpgFrameCountLabel: "Number of frames to extract",
    vidToJpgQualityNote: "Quality: Always best (maximum quality)",
    vidToJpgExtractButton: "Extract Frames:",
    vidToJpgExtractedHeading: "Extracted Frames:",
    vidToJpgInvalidFile: "Please select a valid video file (MP4, MOV, AVI, etc.)",
    vidToJpgFileTooLarge: "File too large. Please select a video smaller than 1000MB.",
    vidToJpgExtractionFailed: "Extraction failed:",
    vidToJpgExtractionFailedHint: "Please try a different video file or smaller frame count.",
    vidToJpgNoFrames: "No frames to download",
    vidToJpgZipCreated: "Successfully created ZIP with frames:",
    vidToJpgZipFailed: "Failed to create ZIP file",

    hdrTitle: "Remove HDR from Videos",
    hdrSubtitle: "Fix green/muddy colors from iPhone HDR videos",
    hdrDropHere: "Drop videos here or click to browse",
    hdrSelectMultiple: "Select multiple videos at once",
    hdrDropVideosOnly: "Please drop video files only",
    hdrSelectedVideos: "Selected Videos",
    hdrClearAll: "Clear All",
    hdrProcessingFile: "Processing",
    hdrLoadingProcessor: "Loading video processor...",
    hdrProcessingVideos: "Processing videos...",
    hdrRemoveFrom: "Remove HDR from videos:",
    hdrFailedToProcess: "Failed to process",
    hdrFailedToProcessAny: "Failed to process any videos",
    hdrSuccessfullyProcessed: "Successfully processed",
    hdrOf: "of",
    hdrZipDownloaded: "ZIP file downloaded successfully",
    hdrZipDownloadFailed: "Failed to download ZIP file",
    hdrProcessedVideos: "Processed Videos",
    hdrOriginal: "Original",
    hdrProcessed: "Processed",
    hdrCompression: "Compression",
    hdrVideosWord: "videos",

    fileUploaderInvalidImage: "Please select valid image file(s) (.jpg, .png, .gif, .heic, etc.)",
    fileUploaderNonImageIgnored: "{count} non-image files were ignored",
    fileUploaderInvalidVideo: "Please select valid video file(s)",
    fileUploaderNonVideoIgnored: "{count} non-video files were ignored",

    cutterDescription: "Upload multiple videos and cut them all into segments at once",
    cutterUploadedVideos: "Uploaded Videos ({count})",
    cuttingSettings: "Cutting Settings",
    cutModeLabel: "Cut Mode",
    cutModeSegmentsLabel: "By Number of Segments (equal parts)",
    cutModeDurationLabel: "By Segment Duration (minimum time, short remainder added to last segment)",
    numberOfSegmentsLabel: "Number of Segments",
    segmentsCountPrefix: "Segments:",
    customLabel: "Custom:",
    segmentsWord: "segments",
    minSegmentDuration: "Minimum Segment Duration",
    secondsCountPrefix: "Seconds:",
    cutModeDurationNote: "Note: If the remainder is shorter than the specified duration, it will be added to the last segment to avoid short clips.",
    cutAllVideos: "Cut All Videos",
    downloadAllAsZipCount: "Download All as ZIP ({count})",
    processingFilePrefix: "Processing:",
    videoWord: "Video",
    processedSegmentsCount: "Processed Segments ({count})",
    readingDurationViaFfmpeg: "Reading video duration via FFmpeg...",
    cannotDetermineDuration: "Cannot determine video duration",
    processingSegmentToast: "Processing {file}: segment {current}/{total}",
    segmentProcessFailed: "Failed to process segment {index}. Try converting to H.264 first using MOV→MP4 tab.",
    codecNotSupportedCutting: "Video codec not supported for cutting. Convert to H.264 first using MOV→MP4 tab.",
    processingVideoOfToast: "Processing video {current}/{total}: {file}",
    createdSegmentsToast: "{file}: created {count} segments",
    errorProcessingFile: "Error processing {file}: {message}",
    createdSegmentsFromVideos: "Created {segCount} segments from {videoCount} videos",
    noSegmentsToDownload: "No segments to download",
    downloadingSegmentToast: "Downloading segment {index}",

    loadingConverter: "Loading converter...",
    noVideosOrFfmpegNotLoaded: "No videos to convert or FFmpeg not loaded.",
    processingFileToast: "Processing {name}...",
    successfullyConvertedGifs: "Successfully converted to {count} GIF(s)",
    conversionFailedRetry: "Conversion failed. Please try again.",
    conversionFailedWithMessage: "Conversion failed: {message}",
    conversionSettingsHeading: "Conversion Settings",
    tabsListAriaLabel: "Video conversion tools",
    tabTooltipGif: "Convert video to animated GIF",
    tabTooltipMov: "Convert MOV files to MP4 format",
    tabTooltipImg: "Convert images to JPG format",
    tabTooltipVideoJpg: "Extract JPG frames from video",
    tabTooltipCut: "Cut video into segments",
    tabTooltipHdr: "Remove HDR from video files",
    tabTooltipSequential: "Convert multiple videos sequentially",

    preparingVideoFormat: "Preparing video ({ext} → MP4)...",
    outOfMemoryError: "Not enough memory to process this video. Try a smaller file or close other browser tabs.",
    videoPreparedForGif: "Video prepared for GIF conversion",
    failedToPrepareVideo: "Failed to prepare video for conversion",
    ffmpegNotAvailableRetry: "FFmpeg is not available. Please reload the page and try again.",
    videoFileTooLarge: "Video file is too large ({size}MB). Maximum size: {max}MB. Try compressing the video.",
    largeFileWarning: "Large file ({size}MB). Processing may take a few minutes.",
    processingVideoStarted: "Processing video...",
    nowProcessingMp4: "Now processing converted MP4...",
    tooManySegments: "Too many segments ({count}). Maximum for {browser}: {max}. Increase segment duration.",
    manySegmentsWarning: "Large number of segments ({count}) in {browser}. This may take a while.",
    creatingSegmentsFromMp4: "Creating {count} segments of {duration} seconds each from MP4...",
    processingMp4Segment: "Processing MP4 segment {current} of {total}...",
    failedConvertMp4Segment: "Failed to convert MP4 segment {index}: {message}",
    creatingEqualSegments: "Creating {count} equal segments from MP4...",
    failedConvertEqualSegment: "Failed to convert equal MP4 segment {index}: {message}",
    creatingGifFromMp4: "Creating GIF from MP4...",
    mp4ConversionFailedToast: "MP4 conversion failed: {message}",
    failedToLoadFfmpegRetry: "Failed to load FFmpeg. Please try again or check your internet connection.",

    uploadVideoToPreview: "Upload a video to preview",
    resetWord: "Reset",
    playWord: "Play",
    pauseWord: "Pause",

    switchLanguage: "Switch language",

    imgConvertButtonSingular: "Convert {count} image",
    imgConvertButtonPlural: "Convert {count} images",

    ffmpegNotLoadedYet: "FFmpeg is not loaded yet. Please wait or try reloading FFmpeg.",
    failedToConvertGif: "Failed to convert video to GIF",
    sequentialConversionProgress: "Sequential Conversion Progress"
  },
  ru: {
    applicationTitle: "Video Tool",
    applicationDescription: "Инструменты для конвертации видео высокого качества. Без загрузки на сервер - все происходит в вашем браузере.",
    batchProcessingTip: "Если вам нужно конвертировать больше чем 7 видео за 1 раз, откройте несколько вкладок сайта параллельно.",
    uploadVideo: "Загрузить видео",
    uploadYourVideos: "Загрузите ваши видео",
    dropIt: "Отпускайте!",
    dragDropMultiple: "Перетащите видеофайлы сюда или нажмите",
    dragDropSingle: "Перетащите видеофайл сюда или нажмите",
    browseFiles: "Выбрать файлы",
    dragAndDrop: "Перетащите видео сюда",
    orBrowse: "или выберите файл",
    fileType: "MP4, WebM, MOV до 50МБ",
    removeVideo: "Удалить",
    convertToGif: "Конвертировать в GIF",
    downloadGif: "Скачать GIF",
    processing: "Обработка...",
    selectQuality: "Качество:",
    selectSize: "Размер:",
    selectFps: "Кадр/сек:",
    low: "Низкое",
    medium: "Среднее",
    high: "Высокое",
    small: "Маленький",
    original: "Оригинал",
    large: "Большой",
    downloadAs: "Скачать как:",
    createNew: "Создать новый",
    gifCreated: "GIF создан!",
    changeSettings: "Изменить настройки",
    ffmpegError: "Не удалось загрузить инструменты обработки видео.",
    retryLoading: "Попробовать снова",
    browserSecurityError: "Безопасность браузера блокирует необходимую функциональность.",
    crossOriginIsolation: "Этот сайт требует включения изоляции перекрестного происхождения для оптимальной производительности.",
    loadingFFmpeg: "Загрузка инструментов обработки видео...",
    seconds: "Секунд",
    toggleTheme: "Переключить тему",
    darkMode: "Переключить на темную тему",
    lightMode: "Переключить на светлую тему",
    privacyNotice: "Ваша конфиденциальность важна для нас",
    fileNotStored: "Мы не храним ваши файлы",
    
    quality: "Качество",
    frameRate: "Частота кадров",
    fps: "кадр/сек",
    smooth: "Плавно",
    detailed: "Детально",
    highDetail: "Высокая детализация",
    speed: "Скорость",
    slowMotion: "Замедленно",
    normal: "Нормально",
    fast: "Быстро",
    videoSegments: "Сегменты видео",
    standardMode: "Стандартный режим",
    advancedMode: "Расширенный режим",
    noSplitting: "Без разделения",
    segments: "Сегменты",
    advancedUpTo: "До 60 сегментов",
    standardUpTo: "До 20 сегментов",
    dividesVideo: "Разделяет видео на равные сегменты",
    parts: "Частей",
    noParts: "Без разделения",
    warning: "Внимание: Большое количество сегментов может повлиять на производительность",
    dimensions: "Размеры",
    maintainAspectRatio: "Сохранять пропорции",
    width: "Ширина",
    height: "Высота",
    auto: "Авто",
    heightWillBeCalculated: "Высота будет рассчитана автоматически для сохранения пропорций",
    settings: "Настройки",
    preview: "Предпросмотр",
    videoToGif: "Видео в GIF",
    videoToPieces: "Видео на части",
    largeGifWarning: "Предупреждение о большом размере GIF",
    gifsTooLarge: "GIFs слишком большие",
    sizeWarningDescription: "Большие GIF могут вызвать проблемы с производительностью и дольше загружаться",
    
    convertAgain: "Конвертировать снова",
    gifPreview: "Предпросмотр GIF",
    downloadSegment: "Скачать сегмент",
    downloadAll: "Скачать все",
    downloadAsZIP: "Скачать как ZIP",
    creatingZip: "Создание ZIP...",
    preparing: "Подготовка...",
    converting: "Конвертация...",
    convertedGif: "Конвертированный GIF",
    convertedGifs: "Конвертированные GIF",
    
    pleaseUploadVideo: "Пожалуйста, сначала загрузите видео",
    uploadVideoFirst: "Сначала загрузите видео",
    noSegmentsYet: "Сегментов пока нет. Нажмите 'Добавить сегмент', чтобы начать",
    addSegment: "Добавить сегмент",
    segment: "Сегмент",
    remove: "Удалить",
    startTime: "Начальное время",
    endTime: "Конечное время",
    cannotCutVideo: "Невозможно разрезать видео. Пожалуйста, проверьте настройки.",
    cutVideo: "Разрезать видео",
    
    sequentialConversion: "Последовательная конвертация",
    sequentialDescription: "Конвертация видео в равные сегменты фиксированной длительности",
    segmentLength: "Длина сегмента",
    conversionStatus: "Статус конвертации",
    filesToProcess: "Файлы для обработки",
    filesSelected: "файлов выбрано",
    currentlyProcessing: "Обрабатывается",
    segmentsCreated: "Создано сегментов",
    startSequentialConversion: "Начать конвертацию",
    downloadAllAsZip: "Скачать всё как ZIP",
    "5seconds": "5 Секунд",
    "10seconds": "10 Секунд",
    customSeconds: "Произвольное количество секунд",
    allVideosProcessed: "Все видео обработаны",
    uploadFilesFirst: "Сначала загрузите файлы",
    noFilesSelected: "Файлы не выбраны",
    error: "Ошибка",
    failedToConvert: "Не удалось конвертировать",
    ffmpegNotLoaded: "Инструменты обработки видео не загружены",
    noGifsToDownload: "Нет GIF для скачивания",
    downloadError: "Ошибка скачивания",
    tabSwitchWarning: "⚠️ ВАЖНО: Не переключайтесь на другие вкладки во время обработки видео! Это может остановить процесс конвертации.",
    videoCutter: "Обрезка видео",
    processingComplete: "Обработка завершена",
    settingsHelpText: "Настройте качество, частоту кадров и размеры перед конвертацией",
    qualityTooltip: "Чем выше качество, тем больше размер файла и дольше конвертация",
    fpsTooltip: "Кадров в секунду: чем больше значение, тем плавнее движение, но больше размер файла",
    pageNotFound: "Упс! Страница не найдена",
    returnToHome: "Вернуться на главную",

    download: "Скачать",
    convertedImages: "Конвертированные изображения",

    movToMp4Title: "Конвертер MOV/HEVC в MP4",
    movToMp4Description: "Конвертируйте MOV и HEVC (H.265) файлы в совместимый MP4 (H.264)",
    movToMp4DropDefault: "Нажмите, чтобы выбрать, или перетащите MOV-файл",
    movToMp4DropActive: "Отпустите MOV-файл здесь",
    movToMp4StepInit: "Инициализация FFmpeg...",
    movToMp4StepProcessingFile: "Обработка файла...",
    movToMp4StepConverting: "Конвертация видео...",
    movToMp4StepPreparing: "Подготовка к скачиванию...",
    movToMp4StepComplete: "Готово!",
    movToMp4ErrorTimeout: "Превышено время конвертации — файл может быть слишком сложным или повреждён",
    movToMp4ErrorInvalidDrop: "Перетащите файл MOV или MP4",
    movToMp4ErrorHevc: "Не удалось конвертировать видео HEVC/H.265. Этот кодек может быть проблемным для обработки.",
    movToMp4ErrorTimeoutRetry: "Превышено время конвертации. Попробуйте файл меньшего размера или другой формат.",
    movToMp4ErrorPrefix: "Ошибка конвертации:",

    imgToJpgTitle: "Конвертер изображений в JPG",
    imgToJpgDescription: "Конвертируйте HEIC, PNG, JPG и другие форматы изображений в оптимизированный JPG с лучшим качеством",
    safariNoticeTitle: "Уведомление для Safari",
    safariNoticeText: "использует особый способ скачивания ZIP-файлов для надёжной загрузки. Большие файлы могут обрабатываться дольше перед скачиванием.",
    imgSuccessfullyConverted: "Успешно конвертировано",
    imgFallback: "резервный метод",
    imgViaBrowser: "через браузер",
    imgHeicUnsupported: "не удалось конвертировать: HEIC не поддерживается. Экспортируйте в JPG через Windows Photos.",
    imgConversionFailedFor: "Не удалось конвертировать",

    vidToJpgTitle: "ВИДЕО В JPG",
    vidToJpgLoadingProcessor: "Загрузка видеопроцессора...",
    vidToJpgLoadingHint: "Это может занять несколько секунд при первой загрузке.",
    vidToJpgFrameCountLabel: "Количество извлекаемых кадров",
    vidToJpgQualityNote: "Качество: всегда лучшее (максимальное качество)",
    vidToJpgExtractButton: "Извлечь кадры:",
    vidToJpgExtractedHeading: "Извлечено кадров:",
    vidToJpgInvalidFile: "Выберите корректный видеофайл (MP4, MOV, AVI и т.д.)",
    vidToJpgFileTooLarge: "Файл слишком большой. Выберите видео размером менее 1000 МБ.",
    vidToJpgExtractionFailed: "Ошибка извлечения:",
    vidToJpgExtractionFailedHint: "Попробуйте другой видеофайл или меньшее количество кадров.",
    vidToJpgNoFrames: "Нет кадров для скачивания",
    vidToJpgZipCreated: "ZIP успешно создан, кадров:",
    vidToJpgZipFailed: "Не удалось создать ZIP-файл",

    hdrTitle: "Удаление HDR из видео",
    hdrSubtitle: "Исправление зелёных/мутных цветов в HDR-видео с iPhone",
    hdrDropHere: "Перетащите видео сюда или нажмите для выбора",
    hdrSelectMultiple: "Можно выбрать несколько видео сразу",
    hdrDropVideosOnly: "Перетаскивайте только видеофайлы",
    hdrSelectedVideos: "Выбранные видео",
    hdrClearAll: "Очистить всё",
    hdrProcessingFile: "Обработка",
    hdrLoadingProcessor: "Загрузка видеопроцессора...",
    hdrProcessingVideos: "Обработка видео...",
    hdrRemoveFrom: "Удалить HDR из видео:",
    hdrFailedToProcess: "Не удалось обработать",
    hdrFailedToProcessAny: "Не удалось обработать ни одно видео",
    hdrSuccessfullyProcessed: "Успешно обработано",
    hdrOf: "из",
    hdrZipDownloaded: "ZIP-файл успешно скачан",
    hdrZipDownloadFailed: "Не удалось скачать ZIP-файл",
    hdrProcessedVideos: "Обработанные видео",
    hdrOriginal: "Оригинал",
    hdrProcessed: "Обработано",
    hdrCompression: "Сжатие",
    hdrVideosWord: "видео",

    fileUploaderInvalidImage: "Выберите корректные файлы изображений (.jpg, .png, .gif, .heic и т.д.)",
    fileUploaderNonImageIgnored: "{count} файлов, не являющихся изображениями, проигнорировано",
    fileUploaderInvalidVideo: "Выберите корректные видеофайлы",
    fileUploaderNonVideoIgnored: "{count} файлов, не являющихся видео, проигнорировано",

    cutterDescription: "Загрузите несколько видео и разрежьте их все на сегменты сразу",
    cutterUploadedVideos: "Загруженные видео ({count})",
    cuttingSettings: "Настройки нарезки",
    cutModeLabel: "Режим нарезки",
    cutModeSegmentsLabel: "По количеству сегментов (равные части)",
    cutModeDurationLabel: "По длительности сегмента (минимальное время, короткий остаток добавляется к последнему сегменту)",
    numberOfSegmentsLabel: "Количество сегментов",
    segmentsCountPrefix: "Сегментов:",
    customLabel: "Свои:",
    segmentsWord: "сегментов",
    minSegmentDuration: "Минимальная длительность сегмента",
    secondsCountPrefix: "Секунд:",
    cutModeDurationNote: "Примечание: если остаток короче заданной длительности, он будет добавлен к последнему сегменту, чтобы избежать коротких клипов.",
    cutAllVideos: "Нарезать все видео",
    downloadAllAsZipCount: "Скачать всё как ZIP ({count})",
    processingFilePrefix: "Обработка:",
    videoWord: "Видео",
    processedSegmentsCount: "Обработанные сегменты ({count})",
    readingDurationViaFfmpeg: "Определение длительности видео через FFmpeg...",
    cannotDetermineDuration: "Не удалось определить длительность видео",
    processingSegmentToast: "Обработка {file}: сегмент {current}/{total}",
    segmentProcessFailed: "Не удалось обработать сегмент {index}. Сначала сконвертируйте в H.264 через вкладку MOV→MP4.",
    codecNotSupportedCutting: "Кодек видео не поддерживается для нарезки. Сначала сконвертируйте в H.264 через вкладку MOV→MP4.",
    processingVideoOfToast: "Обработка видео {current}/{total}: {file}",
    createdSegmentsToast: "{file}: создано сегментов — {count}",
    errorProcessingFile: "Ошибка обработки {file}: {message}",
    createdSegmentsFromVideos: "Создано сегментов: {segCount} из {videoCount} видео",
    noSegmentsToDownload: "Нет сегментов для скачивания",
    downloadingSegmentToast: "Скачивание сегмента {index}",

    loadingConverter: "Загрузка конвертера...",
    noVideosOrFfmpegNotLoaded: "Нет видео для конвертации или FFmpeg не загружен.",
    processingFileToast: "Обработка {name}...",
    successfullyConvertedGifs: "Успешно сконвертировано в {count} GIF",
    conversionFailedRetry: "Конвертация не удалась. Попробуйте снова.",
    conversionFailedWithMessage: "Ошибка конвертации: {message}",
    conversionSettingsHeading: "Настройки конвертации",
    tabsListAriaLabel: "Инструменты конвертации видео",
    tabTooltipGif: "Конвертировать видео в анимированный GIF",
    tabTooltipMov: "Конвертировать файлы MOV в формат MP4",
    tabTooltipImg: "Конвертировать изображения в формат JPG",
    tabTooltipVideoJpg: "Извлечь JPG-кадры из видео",
    tabTooltipCut: "Разрезать видео на сегменты",
    tabTooltipHdr: "Убрать HDR из видеофайлов",
    tabTooltipSequential: "Последовательно конвертировать несколько видео",

    preparingVideoFormat: "Подготовка видео ({ext} → MP4)...",
    outOfMemoryError: "Недостаточно памяти для обработки этого видео. Попробуйте файл меньшего размера или закройте другие вкладки браузера.",
    videoPreparedForGif: "Видео подготовлено для конвертации в GIF",
    failedToPrepareVideo: "Не удалось подготовить видео к конвертации",
    ffmpegNotAvailableRetry: "FFmpeg недоступен. Перезагрузите страницу и попробуйте снова.",
    videoFileTooLarge: "Видеофайл слишком большой ({size}МБ). Максимальный размер: {max}МБ. Попробуйте сжать видео.",
    largeFileWarning: "Большой файл ({size}МБ). Обработка может занять несколько минут.",
    processingVideoStarted: "Обработка видео...",
    nowProcessingMp4: "Теперь обрабатывается сконвертированный MP4...",
    tooManySegments: "Слишком много сегментов ({count}). Максимум для {browser}: {max}. Увеличьте длительность сегмента.",
    manySegmentsWarning: "Большое количество сегментов ({count}) в {browser}. Это может занять много времени.",
    creatingSegmentsFromMp4: "Создание {count} сегментов по {duration} секунд из MP4...",
    processingMp4Segment: "Обработка сегмента MP4 {current} из {total}...",
    failedConvertMp4Segment: "Не удалось сконвертировать сегмент MP4 {index}: {message}",
    creatingEqualSegments: "Создание {count} равных сегментов из MP4...",
    failedConvertEqualSegment: "Не удалось сконвертировать равный сегмент MP4 {index}: {message}",
    creatingGifFromMp4: "Создание GIF из MP4...",
    mp4ConversionFailedToast: "Ошибка конвертации MP4: {message}",
    failedToLoadFfmpegRetry: "Не удалось загрузить FFmpeg. Попробуйте снова или проверьте интернет-соединение.",

    uploadVideoToPreview: "Загрузите видео для предпросмотра",
    resetWord: "Сбросить",
    playWord: "Воспроизвести",
    pauseWord: "Пауза",

    switchLanguage: "Переключить язык",

    imgConvertButtonSingular: "Конвертировать {count} фото",
    imgConvertButtonPlural: "Конвертировать {count} фото",

    ffmpegNotLoadedYet: "FFmpeg ещё не загружен. Подождите или попробуйте перезагрузить FFmpeg.",
    failedToConvertGif: "Не удалось сконвертировать видео в GIF",
    sequentialConversionProgress: "Прогресс последовательной конвертации"
  },
  uk: {
    applicationTitle: "Video Tool",
    applicationDescription: "Інструменти для конвертації відео високої якості. Без завантаження на сервер - все відбувається у вашому браузері.",
    batchProcessingTip: "Якщо вам потрібно конвертувати більше 7 відео за раз, відкрийте кілька вкладок сайту паралельно.",
    uploadVideo: "Завантажити відео",
    uploadYourVideos: "Завантажте ваші відео",
    dropIt: "Відпускайте!",
    dragDropMultiple: "Перетягніть відеофайли сюди або натисніть",
    dragDropSingle: "Перетягніть відеофайл сюди або натисніть",
    browseFiles: "Вибрати файли",
    dragAndDrop: "Перетягніть відео сюди",
    orBrowse: "або виберіть файл",
    fileType: "MP4, WebM, MOV до 50МБ",
    removeVideo: "Видалити",
    convertToGif: "Конвертувати в GIF",
    downloadGif: "Завантажити GIF",
    processing: "Обробка...",
    selectQuality: "Якість:",
    selectSize: "Розмір:",
    selectFps: "Кадрів/сек:",
    low: "Низька",
    medium: "Середня",
    high: "Висока",
    small: "Малий",
    original: "Оригінал",
    large: "Великий",
    downloadAs: "Завантажити як:",
    createNew: "Створити новий",
    gifCreated: "GIF створено!",
    changeSettings: "Змінити налаштування",
    ffmpegError: "Не вдалося завантажити інструменти обробки відео.",
    retryLoading: "Спробувати знову",
    browserSecurityError: "Безпека браузера блокує необхідну функціональність.",
    crossOriginIsolation: "Цей сайт вимагає увімкнення ізоляції перехресного походження для оптимальної продуктивності.",
    loadingFFmpeg: "Завантаження інструментів обробки відео...",
    seconds: "Секунд",
    toggleTheme: "Перемкнути тему",
    darkMode: "Перемкнути на темну тему",
    lightMode: "Перемкнути на світлу тему",
    privacyNotice: "Ваша конфіденційність важлива для нас",
    fileNotStored: "Ми не зберігаємо ваші файли",
    
    quality: "Якість",
    frameRate: "Частота кадрів",
    fps: "кадрів/сек",
    smooth: "Плавно",
    detailed: "Детально",
    highDetail: "Висока деталізація",
    speed: "Швидкість",
    slowMotion: "Уповільнено",
    normal: "Звичайно",
    fast: "Швидко",
    videoSegments: "Сегменти відео",
    standardMode: "Стандартний режим",
    advancedMode: "Розширений режим",
    noSplitting: "Без поділу",
    segments: "Сегменти",
    advancedUpTo: "До 60 сегментів",
    standardUpTo: "До 20 сегментів",
    dividesVideo: "Розділяє відео на рівні сегменти",
    parts: "Частин",
    noParts: "Без поділу",
    warning: "Увага: Велика кількість сегментів може вплинути на продуктивність",
    dimensions: "Розміри",
    maintainAspectRatio: "Зберігати пропорції",
    width: "Ширина",
    height: "Висота",
    auto: "Авто",
    heightWillBeCalculated: "Висота буде розрахована автоматично для збереження пропорцій",
    settings: "Налаштування",
    preview: "Попередній перегляд",
    videoToGif: "Відео у GIF",
    videoToPieces: "Відео на частини",
    largeGifWarning: "Попередження про великий розмір GIF",
    gifsTooLarge: "GIF занадто великі",
    sizeWarningDescription: "Великі GIF можуть викликати проблеми з продуктивністю і довше завантажуватися",
    
    convertAgain: "Конвертувати знову",
    gifPreview: "Попередній перегляд GIF",
    downloadSegment: "Завантажити сегмент",
    downloadAll: "Завантажити все",
    downloadAsZIP: "Завантажити як ZIP",
    creatingZip: "Створення ZIP...",
    preparing: "Підготовка...",
    converting: "Конвертація...",
    convertedGif: "Конвертований GIF",
    convertedGifs: "Конвертовані GIF",
    
    pleaseUploadVideo: "Будь ласка, спочатку завантажте відео",
    uploadVideoFirst: "Спочатку завантажте відео",
    noSegmentsYet: "Сегментів поки немає. Натисніть 'Додати сегмент', щоб почати",
    addSegment: "Додати сегмент",
    segment: "Сегмент",
    remove: "Видалити",
    startTime: "Початковий час",
    endTime: "Кінцевий час",
    cannotCutVideo: "Неможливо розрізати відео. Будь ласка, перевірте налаштування.",
    cutVideo: "Розрізати відео",
    
    sequentialConversion: "Послідовна конвертація",
    sequentialDescription: "Конвертація відео в рівні сегменти фіксованої тривалості",
    segmentLength: "Довжина сегмента",
    conversionStatus: "Статус конвертації",
    filesToProcess: "Файли для обробки",
    filesSelected: "файлів вибрано",
    currentlyProcessing: "Обробляється",
    segmentsCreated: "Створено сегментів",
    startSequentialConversion: "Почати конвертацію",
    downloadAllAsZip: "Завантажити все як ZIP",
    "5seconds": "5 Секунд",
    "10seconds": "10 Секунд",
    customSeconds: "Довільна кількість секунд",
    allVideosProcessed: "Всі відео оброблені",
    uploadFilesFirst: "Спочатку завантажте файли",
    noFilesSelected: "Файли не вибрані",
    error: "Помилка",
    failedToConvert: "Не вдалося конвертувати",
    ffmpegNotLoaded: "Інструменти обробки відео не завантажені",
    noGifsToDownload: "Немає GIF для завантаження",
    downloadError: "Помилка завантаження",
    tabSwitchWarning: "⚠️ ВАЖЛИВО: Не перемикайтесь на інші вкладки під час обробки відео! Це може зупинити процес конвертації.",
    videoCutter: "Обрізка відео",
    processingComplete: "Обробку завершено",
    settingsHelpText: "Налаштуйте якість, частоту кадрів і розміри перед конвертацією",
    qualityTooltip: "Чим вища якість, тим більший розмір файлу і довша конвертація",
    fpsTooltip: "Кадрів за секунду: чим більше значення, тим плавніший рух, але більший розмір файлу",
    pageNotFound: "Ой! Сторінку не знайдено",
    returnToHome: "Повернутися на головну",

    download: "Завантажити",
    convertedImages: "Конвертовані зображення",

    movToMp4Title: "Конвертер MOV/HEVC у MP4",
    movToMp4Description: "Конвертуйте MOV та HEVC (H.265) файли у сумісний MP4 (H.264)",
    movToMp4DropDefault: "Натисніть, щоб вибрати, або перетягніть MOV-файл",
    movToMp4DropActive: "Відпустіть MOV-файл тут",
    movToMp4StepInit: "Ініціалізація FFmpeg...",
    movToMp4StepProcessingFile: "Обробка файлу...",
    movToMp4StepConverting: "Конвертація відео...",
    movToMp4StepPreparing: "Підготовка до завантаження...",
    movToMp4StepComplete: "Готово!",
    movToMp4ErrorTimeout: "Перевищено час конвертації — файл може бути надто складним або пошкодженим",
    movToMp4ErrorInvalidDrop: "Перетягніть файл MOV або MP4",
    movToMp4ErrorHevc: "Не вдалося конвертувати відео HEVC/H.265. Цей кодек може бути проблемним для обробки.",
    movToMp4ErrorTimeoutRetry: "Перевищено час конвертації. Спробуйте файл меншого розміру або інший формат.",
    movToMp4ErrorPrefix: "Помилка конвертації:",

    imgToJpgTitle: "Конвертер зображень у JPG",
    imgToJpgDescription: "Конвертуйте HEIC, PNG, JPG та інші формати зображень в оптимізований JPG з найкращою якістю",
    safariNoticeTitle: "Повідомлення для Safari",
    safariNoticeText: "використовує особливий спосіб завантаження ZIP-файлів для надійного завантаження. Великі файли можуть оброблятися довше перед завантаженням.",
    imgSuccessfullyConverted: "Успішно конвертовано",
    imgFallback: "резервний метод",
    imgViaBrowser: "через браузер",
    imgHeicUnsupported: "не вдалося конвертувати: HEIC не підтримується. Експортуйте в JPG через Windows Photos.",
    imgConversionFailedFor: "Не вдалося конвертувати",

    vidToJpgTitle: "ВІДЕО У JPG",
    vidToJpgLoadingProcessor: "Завантаження відеопроцесора...",
    vidToJpgLoadingHint: "Це може зайняти кілька секунд під час першого завантаження.",
    vidToJpgFrameCountLabel: "Кількість кадрів для витягнення",
    vidToJpgQualityNote: "Якість: завжди найкраща (максимальна якість)",
    vidToJpgExtractButton: "Витягнути кадри:",
    vidToJpgExtractedHeading: "Витягнуто кадрів:",
    vidToJpgInvalidFile: "Виберіть коректний відеофайл (MP4, MOV, AVI тощо)",
    vidToJpgFileTooLarge: "Файл завеликий. Виберіть відео розміром менше 1000 МБ.",
    vidToJpgExtractionFailed: "Помилка витягнення:",
    vidToJpgExtractionFailedHint: "Спробуйте інший відеофайл або меншу кількість кадрів.",
    vidToJpgNoFrames: "Немає кадрів для завантаження",
    vidToJpgZipCreated: "ZIP успішно створено, кадрів:",
    vidToJpgZipFailed: "Не вдалося створити ZIP-файл",

    hdrTitle: "Видалення HDR з відео",
    hdrSubtitle: "Виправлення зелених/каламутних кольорів у HDR-відео з iPhone",
    hdrDropHere: "Перетягніть відео сюди або натисніть для вибору",
    hdrSelectMultiple: "Можна вибрати кілька відео одразу",
    hdrDropVideosOnly: "Перетягуйте лише відеофайли",
    hdrSelectedVideos: "Вибрані відео",
    hdrClearAll: "Очистити все",
    hdrProcessingFile: "Обробка",
    hdrLoadingProcessor: "Завантаження відеопроцесора...",
    hdrProcessingVideos: "Обробка відео...",
    hdrRemoveFrom: "Видалити HDR з відео:",
    hdrFailedToProcess: "Не вдалося обробити",
    hdrFailedToProcessAny: "Не вдалося обробити жодне відео",
    hdrSuccessfullyProcessed: "Успішно оброблено",
    hdrOf: "з",
    hdrZipDownloaded: "ZIP-файл успішно завантажено",
    hdrZipDownloadFailed: "Не вдалося завантажити ZIP-файл",
    hdrProcessedVideos: "Оброблені відео",
    hdrOriginal: "Оригінал",
    hdrProcessed: "Оброблено",
    hdrCompression: "Стиснення",
    hdrVideosWord: "відео",

    fileUploaderInvalidImage: "Виберіть коректні файли зображень (.jpg, .png, .gif, .heic тощо)",
    fileUploaderNonImageIgnored: "{count} файлів, що не є зображеннями, проігноровано",
    fileUploaderInvalidVideo: "Виберіть коректні відеофайли",
    fileUploaderNonVideoIgnored: "{count} файлів, що не є відео, проігноровано",

    cutterDescription: "Завантажте кілька відео і наріжте їх усі на сегменти одразу",
    cutterUploadedVideos: "Завантажені відео ({count})",
    cuttingSettings: "Налаштування нарізки",
    cutModeLabel: "Режим нарізки",
    cutModeSegmentsLabel: "За кількістю сегментів (рівні частини)",
    cutModeDurationLabel: "За тривалістю сегмента (мінімальний час, короткий залишок додається до останнього сегмента)",
    numberOfSegmentsLabel: "Кількість сегментів",
    segmentsCountPrefix: "Сегментів:",
    customLabel: "Власні:",
    segmentsWord: "сегментів",
    minSegmentDuration: "Мінімальна тривалість сегмента",
    secondsCountPrefix: "Секунд:",
    cutModeDurationNote: "Примітка: якщо залишок коротший за задану тривалість, він буде доданий до останнього сегмента, щоб уникнути коротких кліпів.",
    cutAllVideos: "Нарізати всі відео",
    downloadAllAsZipCount: "Завантажити все як ZIP ({count})",
    processingFilePrefix: "Обробка:",
    videoWord: "Відео",
    processedSegmentsCount: "Оброблені сегменти ({count})",
    readingDurationViaFfmpeg: "Визначення тривалості відео через FFmpeg...",
    cannotDetermineDuration: "Не вдалося визначити тривалість відео",
    processingSegmentToast: "Обробка {file}: сегмент {current}/{total}",
    segmentProcessFailed: "Не вдалося обробити сегмент {index}. Спочатку сконвертуйте в H.264 через вкладку MOV→MP4.",
    codecNotSupportedCutting: "Кодек відео не підтримується для нарізки. Спочатку сконвертуйте в H.264 через вкладку MOV→MP4.",
    processingVideoOfToast: "Обробка відео {current}/{total}: {file}",
    createdSegmentsToast: "{file}: створено сегментів — {count}",
    errorProcessingFile: "Помилка обробки {file}: {message}",
    createdSegmentsFromVideos: "Створено сегментів: {segCount} з {videoCount} відео",
    noSegmentsToDownload: "Немає сегментів для завантаження",
    downloadingSegmentToast: "Завантаження сегмента {index}",

    loadingConverter: "Завантаження конвертера...",
    noVideosOrFfmpegNotLoaded: "Немає відео для конвертації або FFmpeg не завантажено.",
    processingFileToast: "Обробка {name}...",
    successfullyConvertedGifs: "Успішно сконвертовано у {count} GIF",
    conversionFailedRetry: "Конвертація не вдалася. Спробуйте ще раз.",
    conversionFailedWithMessage: "Помилка конвертації: {message}",
    conversionSettingsHeading: "Налаштування конвертації",
    tabsListAriaLabel: "Інструменти конвертації відео",
    tabTooltipGif: "Конвертувати відео в анімований GIF",
    tabTooltipMov: "Конвертувати файли MOV у формат MP4",
    tabTooltipImg: "Конвертувати зображення у формат JPG",
    tabTooltipVideoJpg: "Витягнути JPG-кадри з відео",
    tabTooltipCut: "Нарізати відео на сегменти",
    tabTooltipHdr: "Прибрати HDR з відеофайлів",
    tabTooltipSequential: "Послідовно конвертувати кілька відео",

    preparingVideoFormat: "Підготовка відео ({ext} → MP4)...",
    outOfMemoryError: "Недостатньо пам'яті для обробки цього відео. Спробуйте файл меншого розміру або закрийте інші вкладки браузера.",
    videoPreparedForGif: "Відео підготовлено для конвертації в GIF",
    failedToPrepareVideo: "Не вдалося підготувати відео до конвертації",
    ffmpegNotAvailableRetry: "FFmpeg недоступний. Перезавантажте сторінку і спробуйте знову.",
    videoFileTooLarge: "Відеофайл завеликий ({size}МБ). Максимальний розмір: {max}МБ. Спробуйте стиснути відео.",
    largeFileWarning: "Великий файл ({size}МБ). Обробка може зайняти кілька хвилин.",
    processingVideoStarted: "Обробка відео...",
    nowProcessingMp4: "Тепер обробляється сконвертований MP4...",
    tooManySegments: "Забагато сегментів ({count}). Максимум для {browser}: {max}. Збільште тривалість сегмента.",
    manySegmentsWarning: "Велика кількість сегментів ({count}) у {browser}. Це може зайняти багато часу.",
    creatingSegmentsFromMp4: "Створення {count} сегментів по {duration} секунд з MP4...",
    processingMp4Segment: "Обробка сегмента MP4 {current} з {total}...",
    failedConvertMp4Segment: "Не вдалося сконвертувати сегмент MP4 {index}: {message}",
    creatingEqualSegments: "Створення {count} рівних сегментів з MP4...",
    failedConvertEqualSegment: "Не вдалося сконвертувати рівний сегмент MP4 {index}: {message}",
    creatingGifFromMp4: "Створення GIF з MP4...",
    mp4ConversionFailedToast: "Помилка конвертації MP4: {message}",
    failedToLoadFfmpegRetry: "Не вдалося завантажити FFmpeg. Спробуйте знову або перевірте інтернет-з'єднання.",

    uploadVideoToPreview: "Завантажте відео для попереднього перегляду",
    resetWord: "Скинути",
    playWord: "Відтворити",
    pauseWord: "Пауза",

    switchLanguage: "Перемкнути мову",

    imgConvertButtonSingular: "Конвертувати {count} фото",
    imgConvertButtonPlural: "Конвертувати {count} фото",

    ffmpegNotLoadedYet: "FFmpeg ще не завантажено. Зачекайте або спробуйте перезавантажити FFmpeg.",
    failedToConvertGif: "Не вдалося сконвертувати відео в GIF",
    sequentialConversionProgress: "Прогрес послідовної конвертації"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "ru",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("ru");

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    if (!translations[language] || !translations[language][key]) {
      console.warn(`Missing translation for key: ${key}`);
      return translations.en[key] || key;
    }
    return translations[language][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
